### ISSUE TITLE
All `@humanfs/memory` methods don't work

### ISSUE THREAD

**Issue by Deckluhm** [humanwhocodes/humanfs#71]
### Which packages are affected?

- [ ] `@humanfs/core`
- [ ] `@humanfs/node`
- [ ] `@humanfs/deno`
- [X] `@humanfs/memory`
- [ ] `@humanfs/web`
- [ ] `@humanfs/test`
- [ ] `@humanfs/types`

### Environment

Node version: **18.19.0** and **21.6.1**
npm version: **10.4.0**
Deno version: N/A
Operating System: WSL (**Ubuntu 22.04** on Windows 11)

### What did you do?

I tried to use some `@humanfs/memory` methods in my unit tests and I couldn't make them work.

Ended up testing all of them and couldn't make any of them work.

### What did you expect to happen?

Expected them to work!

### What actually happened?

All errors look like this one:
```
file:///home/arnaud/dev/hfs-memory-volume-directories/node_modules/@humanfs/memory/src/memory-hfs.js:104
                let entry = object[part];
                                  ^

TypeError: Cannot read properties of undefined (reading 'world.txt')
    at writePath (file:///home/arnaud/dev/hfs-memory-volume-directories/node_modules/@humanfs/memory/src/memory-hfs.js:104:21)
    at MemoryHfsImpl.write (file:///home/arnaud/dev/hfs-memory-volume-directories/node_modules/@humanfs/memory/src/memory-hfs.js:254:10)
    at #callImplMethod (file:///home/arnaud/dev/hfs-memory-volume-directories/node_modules/@humanfs/core/src/hfs.js:248:32)
    at MemoryHfs.write (file:///home/arnaud/dev/hfs-memory-volume-directories/node_modules/@humanfs/core/src/hfs.js:313:30)
    at file:///home/arnaud/dev/hfs-memory-volume-directories/write.js:3:11
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:120:12)
```

### Link to Minimal Reproducible Example

https://github.com/Deckluhm/hfs-memory-methods

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by nzakas** [comment]
Confirmed. Thanks for the report.
